### ISSUE TITLE
TensorFlow v1.12 is no longer available

### ISSUE THREAD

**Issue by nicanor5** [bedapudi6788/seqtag-keras#1]
Hello,

This module is asking for TensorFlow v1.12 which is no longer available to install using pip, so it becomes impossible to install through pip.

I will try to install using setup.py changing the required TF version.

Any help would be appreciated.

Thanks.

**Comment by bedapudi6788** [comment]
@nicanor5 i will update this library when i get sometime. Also, unless you are using python >= 3.7, v1.12 should be available.

**Comment by bedapudi6788** [comment]
@nicanor5 both seqtag-keras and deepsegment are now updated and will work with the latest versions of tensorflow and keras.

**Comment by nicanor5** [comment]
Thank you so much :)
