### ISSUE TITLE
Constrain version of Keras used to <=2.3.1

### ISSUE THREAD

**Issue by Harrison88** [bedapudi6788/seqtag-keras#2]
Hi,

As discussed in https://github.com/notAI-tech/deepsegment/issues/33, certain versions of Keras are having compatibility issues with Tensorflow. My problem is that my project uses Poetry to manage dependencies. I'm also using DeepSegment, which uses this, which doesn't specify which versions of Keras work, so Poetry keeps trying to update Keras every time I update anything else. I'm having to manually edit my lockfile to keep Keras from updating.

I believe the solution is simple: just add a version number to the setup.py file. Something like `Keras<=2.3.1` should do it. This can always be changed if/when the compatibility issue is solved. I'm happy to write a pull request for this, if you'd like.

Thanks!

**Comment by bedapudi6788** [comment]
added and pushed the new version to PyPI.

**Comment by Harrison88** [comment]
Awesome, thank you for your quick response.
